# Khởi tạo mảng


In [43]:
import numpy as np
#tạo một mảng một chiều
arr_1 = np.array([1, 2, 3, 4, 5])
print(arr_1)
print(arr_1.shape) #kich thuoc cua mang
print("dim = ",arr_1.ndim) #số chiều

[1 2 3 4 5]
(5,)
dim =  1


In [34]:
# tạo một mảng 2 chiều
arr_2 = np.array([[1, 2, 3, 4, 5],[3, 4, 3, 4, 3]])
print(arr_2)
print(arr_2.shape) #kich thuoc cua mang
print("dim = ",arr_2.ndim) #số chiều

[[1 2 3 4 5]
 [3 4 3 4 3]]
(2, 5)
dim =  2


In [35]:
# tạo một mảng 3 chiều
arr_3 = np.array([[[1,4], [2,6], [3,5]],[[1,4], [2,6], [3,5]]])
print(arr_3)
print(arr_3.shape) #kich thuoc cua mang
print("dim = ",arr_3.ndim) #số chiều

[[[1 4]
  [2 6]
  [3 5]]

 [[1 4]
  [2 6]
  [3 5]]]
(2, 3, 2)
dim =  3


In [42]:
#tạo một mảng 4D
arr = np.array([1, 2, 3, 4], ndmin=4)
print(arr)
print('number of dimensions :', arr.ndim)

[[[[1 2 3 4]]]]
number of dimensions : 4


# index

giả sử mảng có n phần tử

khi đó index của mảng sẽ bắt đầu từ 0 -> (n-1)

In [44]:
arr_1 = np.array([1, 2, 3, 4, 5])
for i in range(len(arr_1)):
    print("arr["+str(i)+"]=", arr_1[i])

arr[0]= 1
arr[1]= 2
arr[2]= 3
arr[3]= 4
arr[4]= 5


In [27]:
arr_2 = np.array([[1, 2, 3, 4, 5],[3, 4, 3, 4, 3]])
for i in range(len(arr_2)):
    for j in range(len(arr_2[i])):
        print("arr_2["+str(i)+"]["+str(j)+"]=", arr_2[i][j])

arr_2[0][0]= 1
arr_2[0][1]= 2
arr_2[0][2]= 3
arr_2[0][3]= 4
arr_2[0][4]= 5
arr_2[1][0]= 3
arr_2[1][1]= 4
arr_2[1][2]= 3
arr_2[1][3]= 4
arr_2[1][4]= 3


In [28]:
arr_3 = np.array([[[1,4], [2,6], [3,5]],[[1,4], [2,6], [3,5]]])
for i in range(len(arr_3)):
    for j in range(len(arr_3[i])):
        for k in range(len(arr_3[i][j])):
            print("arr_3["+str(i)+"]["+str(j)+"]["+str(k)+"]=", arr_3[i][j][k])

arr_3[0][0][0]= 1
arr_3[0][0][1]= 4
arr_3[0][1][0]= 2
arr_3[0][1][1]= 6
arr_3[0][2][0]= 3
arr_3[0][2][1]= 5
arr_3[1][0][0]= 1
arr_3[1][0][1]= 4
arr_3[1][1][0]= 2
arr_3[1][1][1]= 6
arr_3[1][2][0]= 3
arr_3[1][2][1]= 5


# Slicing

In [45]:
#lấy các phần tử từ có index từ 1- 4
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [48]:
#lấy các phần tử từ có index từ 2 đến hết mảng
print(arr[2:])
print(arr[2])
#lấy các phần tử từ đầu mảng đến phần tử có index là 4
print(arr[:5])
print(arr[4])

[3 4 5 6 7]
3
[1 2 3 4 5]
5


#### Negative Slicing

In [51]:
# Nagetive index : -n -> -1
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr)
for i in range(-len(arr), 0):
    print("arr["+str(i)+"]=", arr[i])

[1 2 3 4 5 6 7]
arr[-7]= 1
arr[-6]= 2
arr[-5]= 3
arr[-4]= 4
arr[-3]= 5
arr[-2]= 6
arr[-1]= 7


In [55]:
#Negative Slicing
# slicning từ index 2 -> 5 ( -5 -> -2)
print(arr[2:6])
print(arr[-5:-1])

[3 4 5 6]
[3 4 5 6]


##### STEP

In [58]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:6:2])

[2 4 6]


In [60]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2]) # step = 2

[1 3 5 7]


In [62]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
#lấy phần tử thứ 2 của arr, từ mảng con đó lấy các phần tử từ có index 1- 3
arr_1 = arr[1]
print(arr_1[1:4])
print(arr[1, 1:4])

[7 8 9]
[7 8 9]


In [71]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# lấy tất cả các phần tử thứ 2 của các mảng con
print(arr)
print(arr[:,1])
# lấy tất cả các phần tử thứ 3 của các mảng con
print(arr)
print(arr[:,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[2 7]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[3 8]


In [82]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
print(arr[0:2, 1:4])#lấy index từ 1->3 của các mảng con arr[1], arr[2]
print("tuong duong")
print(np.array([arr[0][1:4], arr[1][1:4]]))
print("____________________________________________")
print(arr)
print(arr[0:1, 1:4])#lấy index từ 1->3 của các mảng con arr[1]
print("tuong duong")
print(np.array([arr[0][1:4]]))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[2 3 4]
 [7 8 9]]
tuong duong
[[2 3 4]
 [7 8 9]]
____________________________________________
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[2 3 4]]
tuong duong
[[2 3 4]]


# Type

In [83]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [84]:
arr = np.array(['a', 'a', 'a'])
print(arr.dtype)
arr = np.array(['1', '2', '3'])
print(arr.dtype)

<U1
<U1


In [91]:
#integer
arr = np.array([1, 2, 3, 4], dtype='i')
print(arr)
print(arr.dtype)
#String
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)
#float
arr = np.array([1, 2, 3, 4], dtype='f')
print(arr)
print(arr.dtype)
#int64
arr = np.array([1, 2, 3, 4], dtype='int64')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32
[b'1' b'2' b'3' b'4']
|S1
[1. 2. 3. 4.]
float32
[1 2 3 4]
int64


#### Eror

In [92]:
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

#### Convert

In [96]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)
print("_________________________________")
arr = np.array([1.1, 2.1, 3.1],'i')
print(arr)
print(arr.dtype)

[1 2 3]
int32
_________________________________
[1 2 3]
int32


In [98]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('bool')
print(newarr)
print(newarr.dtype)
print("_________________________________")
arr = np.array([1.1, 2.1, 3.1],'bool')
print(arr)
print(arr.dtype)

[ True  True  True]
bool
_________________________________
[ True  True  True]
bool


# Reshape 

chuyển mảng 1D về nD với điều kiện số phần tử nD phải bằng mảng cũ nói cách khác số phần tử mảng 1D cần phải nấp đầy nD
ví dụ chuyển 1D có 10 phần tử thành n x m x k khi n*m*k = len(1D)

In [ ]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3) #3*4 = 12

print(newarr)

#### Eror

In [102]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13])

newarr = arr.reshape(4, 3) #3*4 = 12 != 13

print(newarr)

ValueError: cannot reshape array of size 13 into shape (4,3)

# OPERATOR

In [103]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr*2)

[ 2  4  6  8 10 12 14]


In [104]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr +2)

[3 4 5 6 7 8 9]


In [111]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr_2 = np.array([1, 7, 3, 6, 5,8 , 7])
print(arr.shape, arr_2.shape)
print(arr + arr_2)
# điều kiện cộng hai mảng là phải cùng SHAPE

(7,) (7,)
[ 2  9  6 10 10 14 14]


In [110]:
# eror 
arr   = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr_2 = np.array([1, 7, 3, 6, 5, 8, 7])
print(arr.shape, arr_2.shape)
print(arr + arr_2) 
# điều kiện cộng hai mảng là phải cùng SHAPE

(8,) (7,)


ValueError: operands could not be broadcast together with shapes (8,) (7,) 

# RANDOM


In [112]:
from numpy import random

x = random.randint(100)

print(x)

22


In [113]:
x=random.randint(100, size=(5))

print(x)

[17 11 65 16 33]


In [116]:
x = random.randint(100, size=(3, 5)) #(3, 5) là shape của mảng cần khởi tạo

print(x)

[[35 92 59 18 41]
 [83 97 10 86 12]
 [ 0 23 18 25 78]]


In [118]:
#khỏi tạo random mảng 5 phần tử theo phân phối chuẩn  0 < X < 1
x = random.rand(5) 
print(x)

[0.16591065 0.206218   0.33888767 0.01933034 0.92851265]


In [119]:
x = random.rand(3, 5)

print(x)

[[0.59871879 0.99368272 0.1126489  0.09840443 0.08607695]
 [0.35188951 0.13065169 0.64122768 0.73168294 0.84212046]
 [0.40225699 0.68754383 0.28805102 0.58250673 0.62452836]]


In [120]:
#chọn phần tử bất kì trong mảng
x = random.choice([3, 5, 7, 9])

print(x)

5


In [124]:
#tạo mảng 2D có shape =( 3, 5) với các phần tử được chọn ngẫu nhiên trong mảng [3, 5, 7, 9]
x = random.choice([3, 5, 7, 9], size=(3, 5))
print(x)

[[5 5 3 9 5]
 [5 3 9 7 3]
 [3 3 9 3 3]]
